
# SEO settings
title: "Dr Josh Higgins"
title2: "" # default: ""
description: "doing HPC stuff"
keywords: ""
url: https://joshh.info # site url
baseurl: null # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

disqus_shortname: "joshhinfo"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
